name: Daily RP Update

on:
  schedule:
    - cron: '0 16 * * *'  # 北京时间每天00:00 (UTC+8)
  workflow_dispatch:       # 允许手动触发

jobs:
  update-rp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 必须获取完整提交历史
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Generate RP
        run: |
          # 生成1-100随机数
          RANDOM_NUM=$(( $RANDOM % 100 + 1 ))

          # 生成评语
          if [ $RANDOM_NUM -le 30 ]; then
            COMMENT="今天的rp似乎有点低..."
          elif [ $RANDOM_NUM -le 70 ]; then
            COMMENT="普普通通的一天呢~"
          else
            COMMENT="rp爆表,快去写题！"
          fi

          # 替换README内容
          sed -i "s/\(**\)\{0,1\}1d100=[0-9]\+\(**\)\{0,1\}/**1d100=$RANDOM_NUM**/g" README.md
          sed -i "/今日rp/{n;n; s/\".*\"/\"$COMMENT\"/}" README.md

      - name: Commit changes
        run: |
          # 检查是否有实际修改
          if git diff --exit-code; then
            echo "没有检测到文件变更"
            exit 0
          fi

          # 解决可能存在的冲突
          git pull origin main --rebase --autostash

          # 提交并推送
          git add README.md
          git commit -m "Auto update daily RP (RP值: $RANDOM_NUM)"
          git push origin main --force-with-lease
